#!/bin/bash
IMAGE="kali-rolling:latest"

if [[ ! -d $HOME/Workspace ]];then
	mkdir -p $HOME/Workspace
fi

if [[ ! -f $HOME/.zsh_history ]];then
	touch $HOME/.zsh_history
fi

docker run -it --rm \
	--cap-add=NET_ADMIN \
	--cap-add=NET_RAW \
	--cap-add=SYS_ADMIN \
	--device /dev/dri \
	--device /dev/net/tun \
	--device /dev/ppp \
	--device /dev/snd \
	--device /dev/fuse \
	--group-add sudo \
	--sysctl net.ipv6.conf.all.disable_ipv6=0 \
	--name kali \
	--user $USER \
	-e XDG_RUNTIME_DIR=$HOME/.run/$(id -u) \
	-e DISPLAY=$DISPLAY \
	-e MANROFFOPT="-c" \
	-e _JAVA_AWT_WM_NONREPARENTING=1 \
	-e _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=gasp' \
	-v $HOME/Workspace:$HOME/Workspace \
	-v $HOME/Downloads:$HOME/Downloads \
	-v $HOME/.zsh_history:$HOME/.zsh_history \
	-v $HOME/bugbox/config/.gf:$HOME/.gf \
	-v $HOME/bugbox/config/.tmux.conf:$HOME/.tmux.conf \
	-v $HOME/bugbox/config/.zshrc:$HOME/.zshrc \
	-v $HOME/bugbox/config/.func:$HOME/.func \
	-v $HOME/bugbox/config/.gf-completion.zsh:$HOME/.gf-completion.zsh \
	-v /dev/shm:/dev/shm:z \
	-v /etc/localtime:/etc/localtime:ro \
	-v /run/dbus/system_bus_socket:/run/dbus/system_bus_socket \
	-v $HOME/Tools:/opt/tools \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	-w $HOME \
	${IMAGE} zsh